#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../conf.d/include/postgres
source /etc/conf.d/include/postgres
# shellcheck source=../../../conf.d/include/repmgr
source /etc/conf.d/include/repmgr

# Current Working Directory
CWD=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

# Initialize conf.d
# shellcheck disable=SC2086
for SCRIPT in $(find ${CWD}/conf.d/* | sort -n) ; do
  chmod +x "${SCRIPT}"
  # Execute in subshell
  ("${SCRIPT}")
done
