#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../functions
source /etc/functions
# shellcheck source=env
source /etc/s6-overlay/s6-rc.d/init-postgres-config/env
# shellcheck source=func
source /etc/s6-overlay/s6-rc.d/init-postgres-config/func
# shellcheck source=env
source /etc/s6-overlay/s6-rc.d/init-repmgr-config/env
# shellcheck source=env
source /etc/s6-overlay/s6-rc.d/init-repmgr-config/func

# Current Working Directory
CWD=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

# Initialize conf.d
# shellcheck disable=SC2086
for SCRIPT in $(find ${CWD}/conf.d/* | sort -n) ; do
  chmod +x "${SCRIPT}"
  # Execute in subshell
  ("${SCRIPT}")
done
