# Alpine version will define the postgresql version to be used
ARG ALPINE_VERSION
ARG DOCKER_PROXY

FROM ${DOCKER_PROXY}/linuxserver/baseimage-alpine:${ALPINE_VERSION} as postgresql

RUN apk upgrade --update --force-overwrite --no-cache && \
    apk add --update --force-overwrite --no-cache \
    acl \
    bash \
    ca-certificates \
    coreutils \
    findutils \
    shadow \
    sudo \
    tzdata \
    rsync && \
    echo "abc ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/abc && \
    chmod 600 /etc/sudoers.d/abc && \
    sync

RUN apk add --update --force-overwrite --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/v3.8/main \
    postgresql=10.12-r0 \
    postgresql-client=10.12-r0 \
    perl=5.26.3-r0 \
    postgresql-plperl=10.12-r0 \
    postgresql-plperl-contrib=10.12-r0 \
    python3=3.6.9-r1 \
    postgresql-plpython3=10.12-r0 \
    postgresql-plpython3-contrib=10.12-r0 \
    tcl=8.6.7-r0 \
    postgresql-pltcl=10.12-r0 \
    postgresql-contrib=10.12-r0 \
    pgtcl

RUN apk add --update --force-overwrite --no-cache --force-broken-world \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf


# Runtime container
FROM postgresql as runtime

ARG BUILD_DATE
ARG CI_PROJECT_NAME
ARG CI_PROJECT_URL
ARG VCS_REF
ARG DOCKER_IMAGE
ARG ALPINE_VERSION
ARG PSQL_VERSION

ENV LANG='C' \
    MUSL_LOCPATH='C' \
    HOME=/config \
    S6_BEHAVIOUR_IF_STAGE2_FAILS=2 \
    S6_SYNC_DISKS=1 \
    PG_COMMAND=/usr/bin/postgres

HEALTHCHECK --interval=10s --timeout=5s --start-period=60s --retries=3 CMD [ "pg_isready",  "-U",  "postgres" ]

EXPOSE 5432/tcp

WORKDIR ${HOME}
VOLUME [ "${HOME}" ]

COPY rootfs/ /

LABEL \
    maintainer="G.J.R. Timmer <gjr.timmer@gmail.com>" \
    org.label-schema.schema-version="1.0" \
    org.label-schema.build-date=${BUILD_DATE} \
    org.label-schema.name=${CI_PROJECT_NAME} \
    org.label-schema.url="${CI_PROJECT_URL}" \
    org.label-schema.vcs-url="${CI_PROJECT_URL}.git" \
    org.label-schema.vcs-ref=${VCS_REF} \
    org.label-schema.docker.image="${DOCKER_IMAGE}" \
    org.label-schema.alpine-version="${ALPINE_VERSION}" \
    org.label-schema.postgresql-version="${PSQL_VERSION}" \
    org.label-schema.license=MIT


# EOF
