# Alpine version will define the postgresql version to be used
ARG ALPINE_VERSION

FROM ghcr.io/linuxserver/baseimage-alpine:${ALPINE_VERSION} as postgresql

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk upgrade --update --no-cache && \
    apk add --update --no-cache \
    acl \
    bash \
    ca-certificates \
    coreutils \
    findutils \
    shadow \
    sudo \
    tzdata \
    postgresql13 \
    postgresql13-plperl \
    postgresql13-plperl-contrib \
    postgresql13-plpython3 \
    postgresql13-plpython3-contrib \
    postgresql13-pltcl \
    postgresql13-contrib \
    postgresql13-jit \
    pgtcl \
    rsync && \
    echo "abc ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/abc && \
    chmod 600 /etc/sudoers.d/abc && \
    sync


# Runtime container
FROM postgresql as runtime

ARG BUILD_DATE
ARG CI_PROJECT_NAME
ARG CI_PROJECT_URL
ARG VCS_REF
ARG DOCKER_IMAGE
ARG ALPINE_VERSION

ENV LANG='en_US.utf8' \
    MUSL_LOCPATH='en_US.utf8' \
    HOME=/config \
    S6_BEHAVIOUR_IF_STAGE2_FAILS=2 \
    S6_SYNC_DISKS=1 \
    PG_COMMAND=/usr/bin/postgres13

HEALTHCHECK --interval=10s --timeout=5s --start-period=60s --retries=3 CMD [ "pg_isready",  "-U",  "postgres" ]

EXPOSE 5432/tcp

WORKDIR ${HOME}
VOLUME [ "${HOME}", "${HOME}/archive" ]

COPY rootfs/ /

LABEL \
    maintainer="G.J.R. Timmer <gjr.timmer@gmail.com>" \
    org.label-schema.schema-version="1.0" \
    org.label-schema.build-date=${BUILD_DATE} \
    org.label-schema.name=${CI_PROJECT_NAME} \
    org.label-schema.url="${CI_PROJECT_URL}" \
    org.label-schema.vcs-url="${CI_PROJECT_URL}.git" \
    org.label-schema.vcs-ref=${VCS_REF} \
    org.label-schema.docker.image="${DOCKER_IMAGE}" \
    org.label-schema.alpine-version="${ALPINE_VERSION}" \
    org.label-schema.license=MIT


# EOF