# Virtual Targets
.PHONY: help


.DEFAULT_GOAL := help


help: ## make target(s)
	@echo "USAGE:\n\tmake <target>\n\n::Global"
	@grep -E '^[a-zA-Z0-9/_-]+:.*?## .*$$' Makefile | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
	@echo
