#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=env.generic
source /etc/conf.d/env.generic

# shellcheck source=fn.generic
source /etc/conf.d/fn.generic
