#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=generic
source /etc/conf.d/include/generic

# shellcheck source=../env.postgres
source /etc/conf.d/env.postgres

# shellcheck source=../fn.postgres
source /etc/conf.d/fn.postgres
