#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=generic
source /etc/conf.d/include/generic

# shellcheck source=../env.repmgr
source /etc/conf.d/env.repmgr

# shellcheck source=../fn.repmgr
source /etc/conf.d/fn.repmgr
