#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../conf.d/include/repmgr
source /etc/conf.d/include/repmgr

# Configure directory
if repmgr_enabled; then
  if [ ! -d "${REPMGR_DATA_DIR}" ]; then
    # Create repmgr data directory
    log-init "creating directory::repmgr [${REPMGR_DATA_DIR}]"
    mkdir -p "${REPMGR_DATA_DIR}"
  else
    log-init "directory::repmgr exists [${REPMGR_DATA_DIR}]"
  fi

  # Fix permissions
  lsiown -R abc:abc "${REPMGR_DATA_DIR}"
fi

# Configure log directory
if repmgr_enabled; then
  if [ ! -d "${REPMGR_LOG_DIR}" ]; then
    # Create repmgr data directory
    log-init "creating directory::log::repmgr [${REPMGR_LOG_DIR}]"
    mkdir -p "${REPMGR_LOG_DIR}"
  else
    log-init "directory::log::repmgr exists [${REPMGR_LOG_DIR}]"
  fi

  # Fix permissions
  lsiown -R abc:abc "${REPMGR_LOG_DIR}"
fi
