#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# Include dependencies
# shellcheck source=../../../etc/functions
source /etc/functions
# shellcheck source=../../../etc/s6-overlay/s6-rc.d/init-postgres-config/env
source /etc/s6-overlay/s6-rc.d/init-postgres-config/env

# Check if retention is set to a number
VALID_NUMBER='^[0-9]+$'
if ! [[ ${PG_LOG_RETENTION} =~ ${VALID_NUMBER} ]] ; then
   echo "error: PG_LOG_RETENTION is not a number" >&2; exit 1
fi

find "${PG_LOG_DIR}" -name '*.log' -mtime "+${PG_LOG_RETENTION}" -print -delete
