#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../../functions
source /etc/functions
# shellcheck source=../env
source /etc/s6-overlay/s6-rc.d/init-postgres-config/env
# shellcheck source=../func
source /etc/s6-overlay/s6-rc.d/init-postgres-config/func

# Validate certificates
if is_enabled "${PG_SSL}"; then
  log-init "SSL/TLS: Enabled"

  if [ ! -f "${PG_CERTS_DIR}/server.crt" ]; then
    log-init "ERROR: SSL/TLS is enabled certificate not found [${PG_CERTS_DIR}/server.crt]"
    exit 41
  else
    if [ "$(stat -c "%a" "${PG_CERTS_DIR}/server.crt")" != "644" ]; then
      log-init "invalid permissions for ${PG_CERTS_DIR}/server.crt; expect: 644"
      exit 42
    fi
  fi

  if [ ! -f "${PG_CERTS_DIR}/server.key" ]; then
    log-init "ERROR: SSL/TLS is enabled certificate key not found [${PG_CERTS_DIR}/server.key]"
    exit 43
  else
    if [ "$(stat -c "%a" "${PG_CERTS_DIR}/server.key")" != "640" ]; then
      log-init "invalid permissions for ${PG_CERTS_DIR}/server.key; expect: 640"
      exit 44
    fi
  fi
fi

# Validate parameters
# This most be completed before we even start creating a data directory
# because when this container runs a node in a repmgr cluster it can even be the
# case that repmgr will be responsible for initializing postgresql.
# Therefor even while we are in 'init-postgres-config' we still need to check
# if some repmgr parameters are valid
if ! psql_is_initialized; then
  case ${REPLICATION_MODE,,} in
    standby|repmgr-standby)
      if repmgr_enabled; then
        : # TODO: Implement repmgr parameter validation
      else
        psql_validate_replicate_params
      fi
    ;;

    snapshot|backup)
      psql_validate_replicate_params
    ;;

    repmgr-witness)
      # NO-OP
    ;;

    *)
      # Validate DB_USER
      if [[ -z ${DB_USER} ]]; then
        log-init "ERROR: required variable DB_USER not set"
        exit 15
      fi
      
      # Validate DB_PASS
      if [[ -z ${DB_PASS} ]]; then
        log-init "ERROR: required variable DB_PASS not set"
        exit 16
      fi
      
      # Validate DB_NAME
      if [[ -z ${DB_NAME} ]]; then
        log-init "ERROR: required variable DB_NAME not set"
        exit 17
      fi
    ;;
  esac
fi
