#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../../conf.d/include/postgres
source /etc/conf.d/include/postgres

# Determine PostgreSQL migration
PG_OLD_VERSION=$(find "${PG_HOME}" -maxdepth 3 -name PG_VERSION_FULL -exec cat {} + 2>/dev/null | grep -o -E '[0-9]{1,2}\.[0-9]{1,2}' | grep -v "${PG_VERSION_SLUG}" | sort -r -n | head -n1)
if [[ -n ${PG_OLD_VERSION} ]]; then

  # Before we mark this for migration, we need to check if this data has
  # already been migrated.
  PG_OLD_DATADIR="${PG_HOME}/${PG_OLD_VERSION}"
  if [ ! -f "${PG_OLD_DATADIR}/.migrated" ]; then
    # Migration is required
    # Enable migration
    PG_OLD_VERSION_MAJOR=$(echo "${PG_OLD_VERSION}" | cut -d '.' -f 1)

    if [ -f "${PG_OLD_DATADIR}/main/postmaster.pid" ]; then
      log-init "postmaster.pid detected in previous data directory; ABORTING"
      exit 1
    fi

    log-init "entering migration mode"
    env_set PG_MIGRATION 1
    env_set PG_OLD_VERSION "${PG_OLD_VERSION}"
    env_set PG_OLD_VERSION_MAJOR "${PG_OLD_VERSION_MAJOR}"
  fi
fi
