#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../../conf.d/include/postgres
source /etc/conf.d/include/postgres

# Configure net-security
case ${REPLICATION_MODE,,} in
  standby|backup|repmgr-standby) ;;
  snapshot)
    psql_configure_hba_security
  ;;

  *)
    psql_configure_hba_security
  ;;
esac
