#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../../functions
source /etc/functions
# shellcheck source=../env
source /etc/s6-overlay/s6-rc.d/init-postgres-config/env
# shellcheck source=../func
source /etc/s6-overlay/s6-rc.d/init-postgres-config/func

# Configure net-security
case ${REPLICATION_MODE,,} in
  standby|backup|repmgr-standby) ;;
  snapshot)
    psql_configure_hba_security
  ;;

  *)
    psql_configure_hba_security
  ;;
esac

# EOF