#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../../functions
source /etc/functions
# shellcheck source=../env
source /etc/s6-overlay/s6-rc.d/init-postgres-config/env
# shellcheck source=../func
source /etc/s6-overlay/s6-rc.d/init-postgres-config/func
# shellcheck source=../../init-repmgr-config/env
source /etc/s6-overlay/s6-rc.d/init-repmgr-config/env
# shellcheck source=../../init-repmgr-config/func
source /etc/s6-overlay/s6-rc.d/init-repmgr-config/func

if repmgr_enabled; then
  if (( REPLICATION_MAX_SENDERS < 10 )); then
    log-init "repmgr: enabled, REPLICATION_MAX_SENDERS < 10; overriding with 10"
    REPLICATION_MAX_SENDERS=10
  fi

  if (( REPLICATION_MAX_SLOTS < 10 )); then
    log-init "repmgr: enabled; REPLICATION_MAX_SLOTS < 10; overriding with 10"
    REPLICATION_MAX_SLOTS=10
  fi
fi

# Max WAL Senders
set_postgresql_param "max_wal_senders" "${REPLICATION_MAX_SENDERS}"

# Max Replication slots
set_postgresql_param "max_replication_slots" "${REPLICATION_MAX_SLOTS}"
