#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../cont-func.d/global
source /etc/cont-func.d/global

# Check is migration is required
psql_determine_migration_required

# EOF