#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../cont-func.d/global
source /etc/cont-func.d/global

# start postgres server internally for the creation of users and databases
rm -rf "${PG_DATA_DIR}/postmaster.pid"
chmod 0700 -R "${PG_DATA_DIR}"
set_postgresql_param "listen_addresses" "127.0.0.1" quiet

case ${REPLICATION_MODE,,} in
  standby|backup|repmgr-standby)
    log-init "skipping due to replication mode = ${REPLICATION_MODE,,}"
  ;;

  *)
    log-init "starting postgres server for configuration"
    # shellcheck disable=SC2086
    s6-setuidgid abc pg_ctl start -D "${PG_DATA_DIR}" -w -t ${PG_TIMEOUT_STARTUP} > /dev/null &
    env_set PG_IN_CONFIG_MODE 1
  ;;
esac

# EOF