#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../cont-func.d/global
source /etc/cont-func.d/global

case ${REPLICATION_MODE,,} in
  standby|backup|repmgr-standby)
    log-init "skipping due to replication mode = ${REPLICATION_MODE,,}"
  ;;

  *)
    # Stopping postgres
    log-init "stopping postgres server; configuration completed"
    # shellcheck disable=SC2086
    s6-setuidgid abc pg_ctl stop -D "${PG_DATA_DIR}" -w -m fast -t ${PG_TIMEOUT_SHUTDOWN}

    # Remove postmaster PID file
    rm -rf "${PG_DATA_DIR}/postmaster.pid"

    # Remove PG_IN_CONFIG_MODE
    env_del PG_IN_CONFIG_MODE
  ;;
esac

# Sync disks
s6-sync
