#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../cont-func.d/global
source /etc/cont-func.d/global

# listen on all interfaces
set_postgresql_param "listen_addresses" "*" quiet
