#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e


################################################################################
# shellcheck source=../../postgresql/functions
source /etc/postgresql/functions


################################################################################
# Start PostgreSQL
# shellcheck disable=SC2086
exec s6-setuidgid abc /usr/bin/postgres -D "${PG_DATA_DIR}"

# EOF