FROM registry.gitlab.timmertech.nl/docker/postgresql:base

# Install PostgreSQL 13
# This will downgrade some other OS packages
# Install highest compatible repmgr
RUN apk --update add --force-overwrite --force-broken-world --no-cache --wait=15 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.16/main \
    postgresql13=13.15-r0 \
    postgresql13-plperl=13.15-r0 \
    postgresql13-plperl-contrib=13.15-r0 \
    postgresql13-plpython3=13.15-r0 \
    postgresql13-plpython3-contrib=13.15-r0 \
    postgresql13-pltcl=13.15-r0 \
    postgresql13-contrib=13.15-r0 \
    postgresql13-jit=13.15-r0 \
    icu-libs=71.1-r2 \
    pgtcl \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    sync

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND} \
    PATH=/lsiopy/bin:/usr/libexec/postgresql13:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
