FROM registry.gitlab.timmertech.nl/docker/postgresql:base

# Install PostgreSQL 15
# This will downgrade some other OS packages
# Install highest compatible repmgr
RUN apk --update add --force-overwrite --no-cache --wait=15 --force-broken-world --repository=http://dl-cdn.alpinelinux.org/alpine/v3.18/main \
    postgresql15=15.7-r0 \
    postgresql15-plperl=15.7-r0 \
    postgresql15-plperl-contrib=15.7-r0 \
    postgresql15-plpython3=15.7-r0 \
    postgresql15-plpython3-contrib=15.7-r0 \
    postgresql15-pltcl=15.7-r0 \
    postgresql15-contrib=15.7-r0 \
    postgresql15-jit=15.7-r0 \
    pgtcl \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    sync

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND} \
    PATH=/lsiopy/bin:/usr/libexec/postgresql15:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
