FROM registry.timmertech.nl/docker/postgresql:base

# Install PostgreSQL 15
# This will downgrade some other OS packages
# Install highest compatible repmgr
RUN apk --update add --force-overwrite --no-cache --wait=15 \
    postgresql15 \
    postgresql15-plperl \
    postgresql15-plperl-contrib \
    postgresql15-plpython3 \
    postgresql15-plpython3-contrib \
    postgresql15-pltcl \
    postgresql15-contrib \
    postgresql15-jit \
    postgresql-pg_cron \
    pgtcl \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    sync

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND} \
    PATH=/lsiopy/bin:/usr/libexec/postgresql15:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
