FROM registry.gitlab.timmertech.nl/docker/postgresql:base

# Install PostgreSQL 9
# This will downgrade some other OS packages
# Install highest compatible repmgr
RUN apk --update add --force-overwrite --no-cache --wait=15 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.6/main \
    postgresql=9.6.13-r0 \
    postgresql-client=9.6.13-r0 \
    perl=5.24.4-r2 \
    postgresql-plperl=9.6.13-r0 \
    postgresql-plperl-contrib=9.6.13-r0 \
    python3=3.6.8-r0 \
    postgresql-plpython3=9.6.13-r0 \
    postgresql-plpython3-contrib=9.6.13-r0 \
    tcl=8.6.6-r0 \
    postgresql-pltcl=9.6.13-r0 \
    postgresql-contrib=9.6.13-r0 \
    pgtcl && \
    apk add --update --no-cache --wait=15 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.13/community \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    sync

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND}
