FROM harbor.local/gitlab/docker/postgresql:base

# Install PostgreSQL 13
# This will downgrade some other OS packages
RUN rm /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/v3.19/main" > /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/v3.19/community" >> /etc/apk/repositories

RUN apk --update add --no-cache --wait=15 \
    postgresql13=13.15-r0 \
    postgresql13-plperl=13.15-r0 \
    postgresql13-plperl-contrib=13.15-r0 \
    postgresql13-plpython3=13.15-r0 \
    postgresql13-plpython3-contrib=13.15-r0 \
    postgresql13-pltcl=13.15-r0 \
    postgresql13-contrib=13.15-r0 \
    postgresql13-jit=13.15-r0 \
    pgtcl \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    sync && \
    pg_versions set-default 13 && \
    echo "Setting default PostgreSQL Version: $(pg_versions get-default)"

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND} \
    PATH=/lsiopy/bin:/usr/libexec/postgresql13:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
