FROM registry.timmertech.nl/docker/postgresql:base

# Install PostgreSQL 10
# This will downgrade some other OS packages
# Install highest compatible repmgr
RUN apk --update add --force-overwrite --no-cache --wait=15 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.8/main \
    postgresql=10.12-r0 \
    postgresql-client=10.12-r0 \
    perl=5.26.3-r0 \
    postgresql-plperl=10.12-r0 \
    postgresql-plperl-contrib=10.12-r0 \
    python3=3.6.9-r1 \
    postgresql-plpython3=10.12-r0 \
    postgresql-plpython3-contrib=10.12-r0 \
    tcl=8.6.7-r0 \
    postgresql-pltcl=10.12-r0 \
    postgresql-contrib=10.12-r0 \
    pgtcl && \
    apk --update add --no-cache --wait=15 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.13/community \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    sync

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND}
