FROM registry.gitlab.timmertech.nl/docker/postgresql:base

# Install PostgreSQL 11
# This will downgrade some other OS packages
# Install highest compatible repmgr
RUN apk --update add --force-overwrite --no-cache --wait=15 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main \
    postgresql=11.12-r0 \
    postgresql-client=11.12-r0 \
    perl=5.28.3-r0 \
    postgresql-plperl=11.12-r0 \
    postgresql-plperl-contrib=11.12-r0 \
    python3=3.7.10-r0 \
    postgresql-plpython3=11.12-r0 \
    postgresql-plpython3-contrib=11.12-r0 \
    tcl=8.6.9-r0 \
    postgresql-pltcl=11.12-r0 \
    postgresql-contrib=11.12-r0 \
    pgtcl && \
    apk --update add --no-cache --wait=15 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.14/community \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    sync

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND}
