FROM registry.timmertech.nl/docker/postgresql:base

# Install PostgreSQL 14
# This will downgrade some other OS packages
# Install highest compatible repmgr
RUN apk add --update --force-overwrite --no-cache \
    postgresql15 \
    postgresql15-plperl \
    postgresql15-plperl-contrib \
    postgresql15-plpython3 \
    postgresql15-plpython3-contrib \
    postgresql15-pltcl \
    postgresql15-contrib \
    postgresql15-jit \
    postgresql-pg_cron \
    pgtcl \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND} \
    PATH=/lsiopy/bin:/usr/libexec/postgresql15:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
