FROM harbor.local/gitlab/docker/postgresql:base

# Install PostgreSQL 12
# This will downgrade some other OS packages
# Update Repositories, revert to alpine 3.15
RUN rm /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/v3.18/main" > /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/v3.18/community" >> /etc/apk/repositories

# Install PostgreSQL 12
RUN apk --update add --no-cache --wait=15 \
    postgresql12=12.19-r0 \
    postgresql12-plperl=12.19-r0 \
    postgresql12-plperl-contrib=12.19-r0 \
    postgresql12-plpython3=12.19-r0 \
    postgresql12-plpython3-contrib=12.19-r0 \
    postgresql12-pltcl=12.19-r0 \
    postgresql12-contrib=12.19-r0 \
    postgresql12-jit=12.19-r0 \
    pgtcl \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    sync && \
    pg_versions set-default 12 && \
    echo "Default PostgreSQL Version: $(pg_versions get-default)"

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND} \
    PATH=/lsiopy/bin:/usr/libexec/postgresql12:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
