FROM harbor.local/gitlab/docker/postgresql:base

# Install PostgreSQL 14
# This will downgrade some other OS packages
# Install highest compatible repmgr
RUN rm /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/v3.15/main" > /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/v3.15/community" >> /etc/apk/repositories

RUN apk --update add --force-overwrite --no-cache --wait=15 \
    postgresql14=14.10-r0 \
    postgresql14-plperl=14.10-r0 \
    postgresql14-plperl-contrib=14.10-r0 \
    postgresql14-plpython3=14.10-r0 \
    postgresql14-plpython3-contrib=14.10-r0 \
    postgresql14-pltcl=14.10-r0 \
    postgresql14-contrib=14.10-r0 \
    postgresql14-jit=14.10-r0 \
    postgresql-pg_cron \
    pgtcl \
    repmgr \
    repmgr-daemon && \
    rm -rf /etc/repmgr.conf && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    sync && \
    pg_versions set-default 14 && \
    echo "Setting default PostgreSQL Version: $(pg_versions get-default)"

COPY rootfs/ /

ARG PG_COMMAND=/usr/bin/postgres
ENV PG_COMMAND=${PG_COMMAND} \
    PATH=/lsiopy/bin:/usr/libexec/postgresql14:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
