#!/bin/bash

source /etc/postgresql/env-defaults

# -----------------------------------------------------------------------------
# MAP UID/GID
PG_UID=${USERMAP_UID:-postgres}
PG_GID=${USERMAP_GID:-postgres}

RUN_UID_GID="${PG_UID}:${PG_GID}"
if [ ${PG_UID} = "postgres" ] && [ ${PG_GID} = "postgres" ]; then
	RUN_UID_GID=postgres
fi

export PG_UID
export PG_GID
export RUN_UID_GID

# -----------------------------------------------------------------------------

PG_CONF=${PG_DATADIR}/postgresql.conf
PG_HBA_CONF=${PG_DATADIR}/pg_hba.conf
PG_IDENT_CONF=${PG_DATADIR}/pg_ident.conf
PG_RECOVERY_CONF=${PG_DATADIR}/recovery.conf
