#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

docker build \
		--build-arg VCS_REF=`git rev-parse --short HEAD` \
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
        --build-arg PGV=$(cat VERSION) \
        --build-arg PGV_SHORT=$(grep -o -E "[0-9]{1,2}\.[0-9]" VERSION) \
		-t $IMAGE_NAME .
