#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
ALPINE_VERSION="$(docker run --rm -t alpine:latest head -1 /etc/alpine-release|tr -d '\r'|grep -o -E "[0-9]{1,2}\.[0-9][0-9]")"
CI_PROJECT_NAME=${CI_PROJECT_NAME:-postgres}
CI_PROJECT_URL=${CI_PROJECT_URL:-$(git config --get remote.origin.url | sed 's/....$$//')}
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA:-$SOURCE_COMMIT}
DOCKER_IMAGE=${DOCKER_IMAGE:-$IMAGE_NAME}

# Build image
docker build --pull \
        --build-arg VCS_REF="${CI_COMMIT_SHORT_SHA}" \
        --build-arg BUILD_DATE="${BUILD_DATE}" \
        --build-arg CI_PROJECT_NAME="${CI_PROJECT_NAME}" \
        --build-arg CI_PROJECT_URL="${CI_PROJECT_URL}" \
        --build-arg DOCKER_IMAGE="${DOCKER_IMAGE}" \
        --build-arg ALPINE_VERSION="${ALPINE_VERSION}" \
        --tag "${IMAGE_NAME}" .

# EOF