#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e


################################################################################
# shellcheck source=../../../cont-psql.d/functions
source /etc/cont-psql.d/functions


################################################################################
# Start PostgreSQL
# shellcheck disable=SC2086
exec s6-setuidgid abc ${PG_COMMAND} -D "${PG_DATA_DIR}"

# EOF