#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../conf.d/include/postgres
source /etc/conf.d/include/postgres
# shellcheck source=../../../conf.d/include/repmgr
source /etc/conf.d/include/repmgr
