#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../../../conf.d/include/cron
source /etc/conf.d/include/cron

# Start cron
if is_enabled "${LOG_REDIRECT}"; then
  # Redirect to stdout
  exec /usr/sbin/crond -f -l 4 -c "${CRON_CRONTAB_DIR}"
else
  exec /usr/sbin/crond -f -l 4 -L "${CRON_LOG_FILE}" -c "${CRON_CRONTAB_DIR}"
fi
