#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../conf.d/include/repmgr
source /etc/conf.d/include/repmgr

if ! repmgr_enabled; then
  s6-svc -O .
  exit 0
fi

log-init "starting repmgrd"

# Wait till database is ready
is_db_ready 1

# Start repmgr
# shellcheck disable=SC2086
exec s6-setuidgid abc repmgrd --verbose --daemonize=false --no-pid-file -f "${REPMGR_CONF}"
