#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Include dependencies
# shellcheck source=../../../functions
source /etc/functions
# shellcheck source=env
source /etc/s6-overlay/s6-rc.d/init-cron-config/env

# shellcheck disable=SC2011
if [[ "$(ls /var/run/s6/container_environment/ | xargs)" == *"FILE__"* ]]; then
  for FILENAME in /var/run/s6/container_environment/*; do
    if [[ "${FILENAME##*/}" == "FILE__"* ]]; then
      SECRETFILE=$(cat "${FILENAME}")
      if [[ -f ${SECRETFILE} ]]; then
        FILESTRIP=${FILENAME//FILE__/}
        cat "${SECRETFILE}" > "${FILESTRIP}"
        echo "[env-init] ${FILESTRIP##*/} set from ${FILENAME##*/}"
      else
        echo "[env-init] cannot find secret in ${FILENAME##*/}"
      fi
    fi
  done
fi

# Configure Shell
if [ ! -f "${HOME}/.bashrc" ]; then
  cp /defaults/skel/.bashrc "${HOME}/.bashrc"
fi

if [ ! -L /root/.bashrc ]; then
  ln -s "${HOME}/.bashrc" /root/.bashrc
fi

if [ ! -f "${HOME}/.bash_aliases" ]; then
  cp /defaults/skel/.bash_aliases "${HOME}/.bash_aliases"
fi

if [ ! -f "${HOME}/.psql_history" ]; then
  touch "${HOME}/.psql_history"
  chown "${PG_USER}:${PG_USER}" "${HOME}/.psql_history"
fi
lsiown abc:abc "${HOME}/.bashrc" "${HOME}/.bash_aliases"

# Set container timezone
cp "/usr/share/zoneinfo/${TZ}" /etc/localtime
log-init "Timezone set to ${TZ}"
