#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# Include dependencies
# shellcheck source=../../../functions
source /etc/functions

# Load Environment Variables
set -o allexport
for ENV in /etc/s6-overlay/s6-rc.d/*/env; do
# shellcheck disable=SC1090
. "${ENV}"
done
set +o allexport

# Print Environment
log-init "Environment Variables:"
MASKED=("PG_PASS" "DB_PASS" "REPLICATION_PASS REPMGR_PASS")
FILTER_SNAPSHOT=("DB_NAME" "DB_USER" "DB_PASS" "PG_PASS" "REPMGR_PASS")
env -0 | sort -z | while IFS='=' read -r -d '' k v; do
  case ${REPLICATION_MODE,,} in
    standby) ;;
    snapshot)
      if [[ " ${FILTER_SNAPSHOT[*]} " =~ $k ]]; then
        continue
      fi
    ;;
    backup) ;;
  esac

  if [ -z "$v" ]; then
    log-init "  $k=<not-set>"
  else
    if [[ " ${MASKED[*]} " =~ $k ]]; then
      log-init "  $k=********"
    else
      log-init "  $k=$v"
    fi
  fi
done
