#!/usr/bin/with-contenv bash
set -e


################################################################################
# shellcheck source=../postgresql/functions
source /etc/postgresql/functions


################################################################################
# Set TimeZone
TZ=${TZ:-UTC}
cp "/usr/share/zoneinfo/${TZ}" /etc/localtime
log-init "Timezone set to ${TZ}"

# EOF