#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../cont-func.d/global
source /etc/cont-func.d/global

# Set container timezone
container_set_timezone

# Configure directories postgres
psql_configure_data_dir
psql_configure_log_dir
psql_configure_run_dir
psql_configure_certs_dir
psql_configure_archive_dir

# Validate Configuration
psql_validate_certs

if ! psql_is_initialized; then
  case ${REPLICATION_MODE,,} in
    standby|repmgr-standby)
      if repmgr_enabled; then
        repmgr_validate_params
      else
        psql_validate_replicate_params
      fi
    ;;

    snapshot|backup)
      psql_validate_replicate_params
    ;;

    repmgr-witness)
      # NO-OP
    ;;

    *)
      psql_configure_initdb_dir

      psql_validate_pgpass
      psql_validate_db_user
      psql_validate_db_pass
      psql_validate_db_name
    ;;
  esac
fi

# configure directories repmgr
repmgr_configure_dir
repmgr_configure_Log_dir

# configure cron
cron_configure_data_dir
cron_configure_task_dir
cron_configure_crontab_dir
cron_configure_log_dir
cron_configure_logrotate_dir
cron_install_logrotate
cron_install_crontab
cron_install_tasks

# EOF