#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../cont-psql.d/functions
source /etc/cont-psql.d/functions

# Set container timezone
container_set_timezone

# Configure directories
psql_configure_data_dir
psql_configure_log_dir
psql_configure_run_dir
psql_configure_certs_dir
psql_configure_archive_dir

# Validate Configuration
psql_validate_certs

if [[ ! -f ${PG_DATA_DIR}/PG_VERSION ]]; then
	case ${REPLICATION_MODE,,} in
    standby)
      psql_validate_replicate_params
    ;;

    snapshot)
      psql_validate_replicate_params
    ;;

    backup)
      psql_validate_replicate_params
    ;;

    *)
      psql_configure_initdb_dir

      psql_validate_pgpass
      psql_validate_db_user
      psql_validate_db_pass
      psql_validate_db_name
    ;;
  esac
fi

# EOF