#!/usr/bin/with-contenv bash
set -e

# Load functions
source /etc/postgresql/functions

if [ ! -d ${PG_HOME} ]; then
	mkdir -p ${PG_HOME}
fi

if [ -d ${PG_DATADIR} ]; then
	find ${PG_DATADIR} -type f -exec chmod 0600 {} \;
	find ${PG_DATADIR} -type d -exec chmod 0700 {} \;
fi

chown -R ${PG_USER}:${PG_USER} ${PG_HOME}

# EOF