#!/usr/bin/with-contenv bash
set -e


################################################################################
# shellcheck source=../postgresql/functions
source /etc/postgresql/functions


################################################################################
# Configure sudo access
if [ ! -f /etc/sudoers.d/abc ]; then
  log-init "setting up sudo access"
  echo "abc ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/abc
  chmod 600 /etc/sudoers.d/abc
fi

# EOF