#!/usr/bin/with-contenv bash
set -e

# Load functions
source /etc/postgresql/functions

# Create Run Directory
if [ ! -d ${PG_RUNDIR} ]; then
	mkdir -p ${PG_RUNDIR} ${PG_RUNDIR}/${PG_VERSION}-main.pg_stat_tmp
fi

# Set Permissions
chmod -R 0755 ${PG_RUNDIR}
chmod g+s ${PG_RUNDIR}
chown -R ${PG_USER}:${PG_USER} ${PG_RUNDIR}

# EOF