#!/usr/bin/with-contenv bash

source /etc/postgresql/functions

# Create Run Directory
mkdir -p ${PG_RUNDIR} ${PG_RUNDIR}/${PG_VERSION}-main.pg_stat_tmp

# Set Permissions
chmod -R 0755 ${PG_RUNDIR}
chmod g+s ${PG_RUNDIR}
chown -R ${PG_UID}:${PG_GID} ${PG_RUNDIR}
