#!/usr/bin/with-contenv bash

source /etc/postgresql/common

# Create Certificate directory
mkdir -p ${PG_CERTDIR}

[[ -f ${PG_CERTDIR}/server.crt ]] && chmod 0644 ${PG_CERTDIR}/server.crt
[[ -f ${PG_CERTDIR}/server.key ]] && chmod 0640 ${PG_CERTDIR}/server.key

# Set permissions
chmod 0755 ${PG_CERTDIR}
chown -R root:${PG_GID} ${PG_CERTDIR}
