#!/usr/bin/with-contenv bash

source /etc/postgresql/functions

# Create Certificate directory
if [ ! -d ${PG_CERTDIR} ]; then
	mkdir -p ${PG_CERTDIR}
fi

if [ -f ${PG_CERTDIR}/server.crt ]; then
	if [ "$(stat -c "%a" ${PG_CERTDIR}/server.crt)" != "644" ]; then
		echo "  Incorrect permissions for ${PG_CERTDIR}/server.crt expect: 644"
	fi
fi

if [ -f ${PG_CERTDIR}/server.key ]; then
	if [ "$(stat -c "%a" ${PG_CERTDIR}/server.key)" != "640" ]; then
		echo "  Incorrect permissions for ${PG_CERTDIR}/server.key expect: 640"
	fi
fi

# Set permissions
chmod 0755 ${PG_CERTDIR}
chown -R root:${PG_GID} ${PG_CERTDIR}
