#!/usr/bin/with-contenv bash
set -e

# Load functions
source /etc/postgresql/functions

if [ ! -d /consul/data ]; then
	mkdir -p /consul/data
fi

if [ ! -d /consul/config ]; then
	mkdir -p /consul/config
fi

chmod -R 0755 /consul
chown -R consul:consul /consul

# EOF