#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../cont-psql.d/functions
source /etc/cont-psql.d/functions

# Load Environment Variables
set -o allexport
# shellcheck source=../cont-psql.d/env-defaults
. /etc/cont-psql.d/env-defaults
set +o allexport

# Print Environment
log-init "Environment Variables:"
MASKED=("PG_PASS" "DB_PASS" "REPLICATION_PASS")
FILTER_SNAPSHOT=("DB_NAME" "DB_USER" "DB_PASS" "PG_PASS")
env -0 | sort -z | while IFS='=' read -r -d '' k v; do
  case ${REPLICATION_MODE,,} in
    standby) ;;
    snapshot)
      if [[ " ${FILTER_SNAPSHOT[*]} " =~ $k ]]; then
        continue
      fi
    ;;
    backup) ;;
  esac

  if [ -z "$v" ]; then
    log-init "  $k=<not-set>"
  else
    # if [ "$k" == "PG_PASS" ] || [ "$k" == "DB_PASS" ] || [ "$k" == "REPLICATION_PASS" ]; then
    #   log-init "  $k=********"
    # else
    #   log-init "  $k=$v"
    # fi
    if [[ " ${MASKED[*]} " =~ $k ]]; then
      log-init "  $k=********"
    else
      log-init "  $k=$v"
    fi
  fi
done

# EOF