#!/usr/bin/with-contenv bash
set -e

# Load functions
source /etc/postgresql/functions

# configure path to data_directory
set_postgresql_param "data_directory" "${PG_DATADIR}"

# configure logging
set_postgresql_param "log_directory" "${PG_LOGDIR}"
set_postgresql_param "log_filename" "postgresql-${PG_VERSION}-main.log"

# EOF