#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../cont-func.d/global
source /etc/cont-func.d/global

# configure logging
set_postgresql_param "log_directory" "${PG_LOG_DIR}"
set_postgresql_param "log_filename" "psql-%Y%m%d.log"

if is_enabled "${PG_LOG_COLLECTOR}"; then
  set_postgresql_param "logging_collector" "on"
fi
set_postgresql_param "log_file_mode" "${PG_LOG_FILE_MODE}"
set_postgresql_param "log_rotation_age" "${PG_LOG_FILE_ROTATION}"

# EOF