#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e


################################################################################
# shellcheck source=../postgresql/functions
source /etc/postgresql/functions


################################################################################
# Configure journal
set_postgresql_param "wal_level" "${PG_JOURNAL_WAL_LEVEL,,}"
set_postgresql_param "wal_keep_segments" "${PG_JOURNAL_WAL_KEEP_SEGMENTS}"
set_postgresql_param "max_wal_senders" "${PG_JOURNAL_MAX_SENDERS}"
set_postgresql_param "checkpoint_segments" "${PG_JOURNAL_CHECKPOINT_SEGMENTS}"

# EOF