#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e
shopt -s extglob

# shellcheck source=../cont-func.d/global
source /etc/cont-func.d/global

# Configure net-security
case ${REPLICATION_MODE,,} in
  standby|backup|repmgr-standby) ;;
  snapshot)
    psql_configure_hba_security
  ;;

  *)
    psql_configure_hba_security
  ;;
esac

# EOF