#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e


################################################################################
# shellcheck source=../postgresql/functions
source /etc/postgresql/functions


################################################################################
# Configure net-security
if [ ! -f "${PG_DATA_DIR}/net-security" ]; then
	log-init "trusting connections from the local network..."
	set_hba_param "host	all				all				samenet					trust"

	# allow remote connections to postgresql database
	set_hba_param "host	all				all				0.0.0.0/0				md5"

	touch "${PG_DATA_DIR}/net-security"
fi

# EOF