#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../postgresql/functions
source /etc/postgresql/functions

# Configure net-security
case ${REPLICATION_MODE,,} in
	standby|backup) ;;
	snapshot)
		psql_configure_net_security
	;;

	*)
		if [ ! -f "${PG_DATA_DIR}/net-security" ]; then
			psql_configure_net_security
		fi
	;;
esac

# EOF