#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../cont-psql.d/functions
source /etc/cont-psql.d/functions

# Max WAL Senders
set_postgresql_param "max_wal_senders" "${REPLICATION_MAX_SENDERS}"

# Max Replication slots
set_postgresql_param "max_replication_slots" "${REPLICATION_MAX_SLOTS}"
