#!/usr/bin/with-contenv bash
set -e

# Load functions
source /etc/postgresql/functions

case $REPLICATION_MODE in
	slave|snapshot|backup) ;;
	*)
		if [ "${PG_CRON}" = true ]; then
			# Preload pg_cron shared libraries
			set_postgresql_param "shared_preload_libraries" "pg_cron"
		fi
	;;
esac
  
# EOF