#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../cont-psql.d/functions
source /etc/cont-psql.d/functions

# Configure pg_cron
case ${REPLICATION_MODE,,} in
	standby|snapshot|backup) ;;
	*)
		if is_enabled "${PG_CRON}"; then
			# Preload pg_cron shared libraries
			set_postgresql_param "shared_preload_libraries" "pg_cron"

			# Set pg_cron database
			set_postgresql_param "cron.database_name" "${PG_CRON_DB}"

			# Configure Background Workers
			if is_enabled "${PG_CRON_WORKERS_BACKGROUND}"; then
				# Schedule jobs via background workers instead of localhost connections
				set_postgresql_param "cron.use_background_workers" "on"

				# Maximum number of background workers
				set_postgresql_param "max_worker_processes" "${PG_CRON_WORKERS_MAX}"
			fi

		fi
	;;
esac

# EOF