#!/usr/bin/with-contenv bash
set -e

# Load functions
source /etc/postgresql/functions

# start postgres server internally for the creation of users and databases
rm -rf ${PG_DATADIR}/postmaster.pid
chmod 0700 -R ${PG_DATADIR}
set_postgresql_param "listen_addresses" "127.0.0.1" quiet
s6-setuidgid ${PG_USER} pg_ctl -D ${PG_DATADIR} -w start > /var/log/postgresql/startup.log &

# EOF