#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e


################################################################################
# shellcheck source=../postgresql/functions
source /etc/postgresql/functions


################################################################################
# start postgres server internally for the creation of users and databases
rm -rf "${PG_DATA_DIR}/postmaster.pid"
chmod 0700 -R "${PG_DATA_DIR}"
set_postgresql_param "listen_addresses" "127.0.0.1" quiet

log-init "starting postgres server for configuration"
# shellcheck disable=SC2086
s6-setuidgid abc pg_ctl start -D "${PG_DATA_DIR}" -w -t ${PG_TIMEOUT_STARTUP} > /dev/null &
