#!/usr/bin/with-contenv bash
set -e


################################################################################
# shellcheck source=../postgresql/functions
source /etc/postgresql/functions


################################################################################
# Check is database is ready to accept operations
is_db_ready


################################################################################
# Configure DB_USER
if [[ -n ${DB_USER} ]]; then
	case ${REPLICATION_MODE,,} in
		slave|snapshot|backup)
			log-init "database user cannot be created on a ${REPLICATION_MODE} node. Skipping..."
		;;

		*)
			log-init "creating database user: ${DB_USER}"
			if [[ -z $(psql -U "${PG_USER}" -Atc "SELECT 1 FROM pg_catalog.pg_user WHERE usename = \"${DB_USER}\"";) ]]; then
				psql -U "${PG_USER}" -c "CREATE ROLE \"${DB_USER}\" with LOGIN CREATEDB PASSWORD \"${DB_PASS}\";" >/dev/null
			fi
		;;
	esac
fi

# EOF