#!/usr/bin/with-contenv bash
set -e

# Load functions
source /etc/postgresql/functions

# Check is database is ready to accept operations
isDBReady

if [[ -n ${DB_NAME} ]]; then
	case $REPLICATION_MODE in
		slave|snapshot|backup) ;;

		*)
			for database in $(awk -F',' '{for (i = 1 ; i <= NF ; i++) print $i}' <<< "${DB_NAME}"); do
				echo "  Creating database: ${database}..."
				if [[ -z $(psql -U ${PG_USER} -Atc "SELECT 1 FROM pg_catalog.pg_database WHERE datname = '${database}'";) ]]; then
					psql -U ${PG_USER} -c "CREATE DATABASE \"${database}\" WITH TEMPLATE = \"${DB_TEMPLATE}\";" >/dev/null
				fi

				if [[ -n ${DB_USER} ]]; then
					echo "  Granting access to ${DB_USER} user..."
					psql -U ${PG_USER} -c "GRANT ALL PRIVILEGES ON DATABASE \"${database}\" to \"${DB_USER}\";" >/dev/null
				fi
			done

			for file in /etc/postgresql/init.d/*.sql; do
				BASENAME=$(basename $file)
				DATABASE=$(awk -F'-' '{print $2}' <<< "${BASENAME}")

				if [[ ! -z $(psql -U ${PG_USER} -Atc "SELECT 1 FROM pg_catalog.pg_database WHERE datname = '${DATABASE}'";) ]]; then
					echo "  Executing ${BASENAME}"
					psql --username ${PG_USER} --dbname ${DATABASE} --file ${file}
				fi
			done

		;;
	esac
fi

# EOF