#!/usr/bin/with-contenv bash
set -e


################################################################################
# shellcheck source=../postgresql/functions
source /etc/postgresql/functions


################################################################################
# Check is database is ready to accept operations
is_db_ready


################################################################################
# Create database
if [[ -n ${DB_NAME} ]]; then
	case ${REPLICATION_MODE,,} in
		slave|snapshot|backup) ;;

		*)
			# shellcheck disable=SC2013
			for database in $(awk -F',' '{for (i = 1 ; i <= NF ; i++) print $i}' <<< "${DB_NAME}"); do
				log-init "creating database: ${database}..."
				if [[ -z $(psql -U "${PG_USER}" -Atc "SELECT 1 FROM pg_catalog.pg_database WHERE datname = '${database}'";) ]]; then
					psql -U "${PG_USER}" -c "CREATE DATABASE \"${database}\" WITH TEMPLATE = \"${DB_TEMPLATE}\";" >/dev/null
				fi

				if [[ -n ${DB_USER} ]]; then
					log-init "granting access to ${DB_USER} user..."
					psql -U "${PG_USER}" -c "GRANT ALL PRIVILEGES ON DATABASE \"${database}\" to \"${DB_USER}\";" >/dev/null
				fi
			done

			# Load Custom SQL files per database
			# The format of the init.db.d directory must have its sql files
			# seperated per database name
			# init.db.d format: ${HOME}/init.db.d/<DATABASE>/*.sql
			find "${PG_INIT_DB}/" -maxdepth 1 -type d -print0 | while read -r -d $'\0' DIR; do
				DB=$(basename "${DIR}")
				for SQL in "${PG_INIT_DB}/${DB}"/*.sql; do
					if [ -f "${SQL}" ]; then
						BASENAME=$(basename "${SQL}")

						if [[ -n $(psql -U "${PG_USER}" -Atc "SELECT 1 FROM pg_catalog.pg_database WHERE datname = '${DB}'";) ]]; then
							log-init "executing [${BASENAME}] on database [${DB}]"
							psql --username "${PG_USER}" --dbname "${DB}" --file "${SQL}"
						fi
					fi
				done
			done

		;;
	esac
fi

# EOF