#!/usr/bin/with-contenv bash
set -e

# Load functions
source /etc/postgresql/functions

if [[ -n ${DB_NAME} ]]; then
	case $REPLICATION_MODE in
		slave|snapshot|backup) ;;
		*)
			if [ "${PG_CRON}" = true ]; then
				echo "  Loading cron scheduler extension"
				psql -U ${PG_USER} -c "CREATE EXTENSION IF NOT EXISTS ${extension};" >/dev/null 2>&1
			fi
		;;
	esac
fi

# EOF