#!/usr/bin/with-contenv bash
set -e

# Load functions
source /etc/postgresql/functions

case $REPLICATION_MODE in
	slave|snapshot|backup) ;;
	*)
		if [ "${PG_CRON}" = true ]; then
			echo "  Loading cron scheduler extension"
			psql -U ${PG_USER} -c "CREATE EXTENSION IF NOT EXISTS ${extension};" >/dev/null 2>&1
			
			if [[ -n ${DB_USER} ]]; then
				echo "  Granting cron access to ${DB_USER} user..."
				psql -U ${PG_USER} -c "GRANT USAGE ON SCHEMA cron TO \"${DB_USER}\";" >/dev/null
			fi
		fi
	;;
esac

# EOF