#!/usr/bin/with-contenv bash
set -e


################################################################################
# shellcheck source=../postgresql/functions
source /etc/postgresql/functions


################################################################################
# Stopping postgres
log-init "stopping postgres server; configuration completed"
s6-setuidgid abc pg_ctl -D "${PG_DATA_DIR}" -w stop >/dev/null

# EOF