#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../cont-psql.d/functions
source /etc/cont-psql.d/functions

# listen on all interfaces
set_postgresql_param "listen_addresses" "*" quiet

# EOF