#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../postgresql/functions
source /etc/postgresql/functions

# Performance tuning
CORES=$(nproc)
MAX_CONN=$(is_greatest $((CORES*4)) 100)
MEM_TOTAL_KB=$(grep -i MemTotal < /proc/meminfo |awk '{print $2}')
MEM_TOTAL_MB=$((MEM_TOTAL_KB/1024))
SHARED_BUFFERS=$(is_least $((MEM_TOTAL_MB/2)) 10240)

# Max Connections
if [ "${PG_MAX_CONNECTIONS,,}" == "auto" ]; then
	# shellcheck disable=SC2086
	set_postgresql_param "max_connections" ${MAX_CONN}
else
	# shellcheck disable=SC2086
	set_postgresql_param "max_connections" ${PG_MAX_CONNECTIONS}
fi

# Shared Buffers
if [ "${PG_SHARED_BUFFERS,,}" == "auto" ]; then
	set_postgresql_param "shared_buffers" "${SHARED_BUFFERS}MB"
else
	# shellcheck disable=SC2086
	set_postgresql_param "shared_buffers" ${PG_SHARED_BUFFERS}
fi

# Work Memory
if [ "${PG_WORK_MEM,,}" == "auto" ]; then
	WORK_MEM=$(($((MEM_TOTAL_MB-SHARED_BUFFERS))/$((CORES*16))))
	set_postgresql_param "work_mem" "${WORK_MEM}MB"
else
	# shellcheck disable=SC2086
	set_postgresql_param "work_mem" ${PG_WORK_MEM}
fi

# Maintenance Work Memory
# shellcheck disable=SC2086
set_postgresql_param "maintenance_work_mem" ${PG_MAINTENANCE_WORK_MEM}

# Effective IO Concurreny
if [ "${PG_EFFECTIVE_IO_CONCURRENCY,,}" == "ssd" ]; then
	set_postgresql_param "effective_io_concurrency" 200
else
	# shellcheck disable=SC2086
	set_postgresql_param "effective_io_concurrency" ${PG_EFFECTIVE_IO_CONCURRENCY}
fi

# Archive Mode
if is_enabled "${PG_ARCHIVE_MODE}"; then
	set_postgresql_param "archive_mode" on
else
	set_postgresql_param "archive_mode" on
fi
