#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008
set -e

# shellcheck source=../../../cont-func.d/global
source /etc/cont-func.d/global

if repmgr_enabled; then
  if ! repmgr_is_initialized && [ -f "${REPMGR_DATA_DIR}/standby.follow" ]; then
    log-init "issuing standby follow"

    # First we need to be able to connect to the master
    is_master_ready 1

    # Now we need to check that we have started up ourself
    is_db_ready_socket 1

    s6-setuidgid abc repmgr -f "${REPMGR_CONF}" standby follow
    rm -f "${REPMGR_DATA_DIR}/standby.follow"
    s6-setuidgid abc touch "${REPMGR_DATA_DIR}/.initialized"
  fi

fi

# EOF
