#!/usr/bin/with-contenv bash

CONSUL=${CONSUL:-0}


if (( ${CONSUL} == 1 )) || [ "${CONSUL}" = "true" ]; then

	CONSUL_UID=$(id -u consul)
	CONSUL_GID=$(id -g consul)
	
	exec s6-applyuidgid -u ${CONSUL_UID} -g ${CONSUL_GID} consul agent -config-dir=/consul/config -data-dir=/consul/data
fi
# EOF