#!/usr/bin/with-contenv bash

CONSUL=${CONSUL:-0}
CONSUL_DEV=${CONSUL_DEV:-0}


if (( ${CONSUL} == 1 )) || [ "${CONSUL}" = "true" ]; then

	CONSUL_UID=$(id -u consul)
	CONSUL_GID=$(id -g consul)
	
	CONSUL_DEV_ARG=${CONSUL_DEV_ARG:-}
	
	if (( ${CONSUL_DEV} == 1 )) || [ "${CONSUL_DEV}" = "true" ]; then
		CONSUL_DEV_ARG="-dev"
	fi
	
	exec s6-applyuidgid -u ${CONSUL_UID} -g ${CONSUL_GID} consul agent ${CONSUL_DEV_ARG} -config-dir=/consul/config -data-dir=/consul/data
fi
# EOF